spring.application.name=BloodBank
server.port=1113
spring.mvc.view.prefix=/Blood/
spring.mvc.view.suffix=.jsp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/BloodBank
spring.datasource.username=root
spring.datasource.password=neha
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.dd1-auto=update
spring.jpa.show.sql=true
spring
